python3 avg_organelle.py --org Cytosol  --pc PC1
python3 avg_organelle.py --org Cytosol  --pc PC2
python3 avg_organelle.py --org Cytosol  --pc PC3
python3 avg_organelle.py --org Cytosol  --pc PC4
python3 avg_organelle.py --org Cytosol  --pc PC5
python3 avg_organelle.py --org Cytosol  --pc PC6
python3 avg_organelle.py --org Microtubules --pc PC1
python3 avg_organelle.py --org Microtubules --pc PC2
python3 avg_organelle.py --org Microtubules --pc PC3
python3 avg_organelle.py --org Microtubules --pc PC4
python3 avg_organelle.py --org Microtubules --pc PC5
python3 avg_organelle.py --org Microtubules --pc PC6
python3 avg_organelle.py --org EndoplasmicR --pc PC1
python3 avg_organelle.py --org EndoplasmicR --pc PC2
python3 avg_organelle.py --org EndoplasmicR --pc PC3
python3 avg_organelle.py --org EndoplasmicR --pc PC4
python3 avg_organelle.py --org EndoplasmicR --pc PC5
python3 avg_organelle.py --org EndoplasmicR --pc PC6
python3 avg_organelle.py --org Aggresome --pc PC1
python3 avg_organelle.py --org Aggresome --pc PC2
python3 avg_organelle.py --org Aggresome --pc PC3
python3 avg_organelle.py --org Aggresome --pc PC5
python3 avg_organelle.py --org Aggresome --pc PC4
python3 avg_organelle.py --org Aggresome --pc PC6
python3 avg_organelle.py --org NuclearM --pc PC1
python3 avg_organelle.py --org NuclearM --pc PC2
python3 avg_organelle.py --org NuclearM --pc PC3
python3 avg_organelle.py --org NuclearM --pc PC4
python3 avg_organelle.py --org NuclearM --pc PC5
python3 avg_organelle.py --org NuclearM --pc PC6
python3 avg_organelle.py --org MitoticS --pc PC1
python3 avg_organelle.py --org MitoticS --pc PC1
python3 avg_organelle.py --org MitoticS --pc PC2
python3 avg_organelle.py --org MitoticS --pc PC3
python3 avg_organelle.py --org MitoticS --pc PC4
python3 avg_organelle.py --org MitoticS --pc PC5
python3 avg_organelle.py --org MitoticS --pc PC6
