python3 avg_organelle.py --org MitoticS  --pc PC2
python3 avg_organelle.py --org MitoticS  --pc PC3
python3 avg_organelle.py --org NuclearB  --pc PC1
python3 avg_organelle.py --org NuclearB  --pc PC2
python3 avg_organelle.py --org NuclearB  --pc PC3
python3 avg_organelle.py --org NuclearB  --pc PC4
python3 avg_organelle.py --org NuclearB  --pc PC5
python3 avg_organelle.py --org IntermediateF  --pc PC1
python3 avg_organelle.py --org IntermediateF  --pc PC2
python3 avg_organelle.py --org IntermediateF  --pc PC3
python3 avg_organelle.py --org IntermediateF  --pc PC4
python3 avg_organelle.py --org IntermediateF  --pc PC5
python3 avg_organelle.py --org Nucleoplasm  --pc PC1
python3 avg_organelle.py --org Nucleoplasm  --pc PC1
python3 avg_organelle.py --org Nucleoplasm  --pc PC2
python3 avg_organelle.py --org Nucleoplasm  --pc PC3
python3 avg_organelle.py --org Nucleoplasm  --pc PC4
python3 avg_organelle.py --org Nucleoplasm  --pc PC5
#python3 avg_organelle.py --org Microtubules  --pc PC6
