python3 avg_organelle.py --org Nucleoli  --pc PC1
python3 avg_organelle.py --org Nucleoli  --pc PC2
python3 avg_organelle.py --org Nucleoli  --pc PC3
python3 avg_organelle.py --org Nucleoli  --pc PC4
python3 avg_organelle.py --org Nucleoli  --pc PC5
python3 avg_organelle.py --org Nucleoli  --pc PC6
python3 avg_organelle.py --org NuclearB  --pc PC1
python3 avg_organelle.py --org NuclearB  --pc PC2
python3 avg_organelle.py --org NuclearB  --pc PC3
python3 avg_organelle.py --org GolgiA  --pc PC1
python3 avg_organelle.py --org GolgiA  --pc PC2
python3 avg_organelle.py --org GolgiA  --pc PC3
python3 avg_organelle.py --org GolgiA  --pc PC4
python3 avg_organelle.py --org GolgiA  --pc PC5
python3 avg_organelle.py --org NuclearB  --pc PC1
python3 avg_organelle.py --org NuclearB  --pc PC2
python3 avg_organelle.py --org NuclearB  --pc PC3
python3 avg_organelle.py --org NuclearS  --pc PC4
python3 avg_organelle.py --org NuclearB  --pc PC5